# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a11ccfa90a38fae1f737e07538036b250f5cc6dcfb37072393fe3821fea6802d8f2a65371981e12f8f8eb4e0e5c4844690c06fcfa21de504310793b5a4ba82b5

test:
  secret_key_base: d9b74441d507d97be69c9f943e2f62569f16b06cd228c8ceabd9b201cb0f50cc06558878fbc55c95350af0f4251a63f3709d06a7b1d4da93e04d950f531e1d9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
