# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d755ed4200df27f32498b6cbcc337d920f08a10010249eec1ba00bca7ea08deeeed58ca79f40a0d8d05e19772cfe1f235f1aafaec07b61107c17079c58de12a

test:
  secret_key_base: ddcef08f2565b7dcc3e0d8aadf9af5f67cbfd468e2fc5a6a25a21df2681089780236db50c97935ce6efc49ac93e94936d7cc5b8cb49323a496da2efa69d38fa6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
